FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY BbsClient.csproj .
RUN dotnet restore
COPY Program.cs .
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /out .
CMD ["dotnet", "BbsClient.dll"]
